name: Build a my dog-nose firmware

on:
  push:
    paths:
      - 'qmk_firmware/keyboards/keyball/**.mk'
      - 'qmk_firmware/keyboards/keyball/**.c'
      - 'qmk_firmware/keyboards/keyball/**.h'
      - 'qmk_firmware/keyboards/keyball/**.json'
      - '.github/**.yml'
    tags-ignore:
      - '*'
    branches:
      - '*'

  pull_request:
    paths:
      - 'qmk_firmware/keyboards/keyball/**.mk'
      - 'qmk_firmware/keyboards/keyball/**.c'
      - 'qmk_firmware/keyboards/keyball/**.h'
      - 'qmk_firmware/keyboards/keyball/**.json'
      - '.github/**.yml'

  workflow_call: {}


jobs:

  build:

    uses: ./.github/workflows/build-firmware.yml
    with:
      qmk_version: '0.22.14'
      keyboard:    'keyball39'
      keymap:      'dog-nose'
